fastp:
  extra_params: "--detect_adapter_for_pe"

star:
  index_dir: "/home/gennaro/data/references/GRCh38/GENCODE/v48/STAR_idx"
  readFilesCommand: "zcat"
  twopassMode: "Basic" 
  outFilterMultimapNmax: 100 
  winAnchorMultimapNmax: 100
  alignSJoverhangMin: 8
  alignSJDBoverhangMin: 1
  outFilterMismatchNmax: 999
  outFilterMismatchNoverLmax: 0.1 
  alignIntronMin: 20 
  alignIntronMax: 1000000 
  alignMatesGapMax: 1000000 
  outFilterScoreMinOverLread: 0.33 
  outFilterMatchNminOverLread: 0.33 
  limitSjdbInsertNsj: 1200000 
  outSAMstrandField: "intronMotif" 
  quantMode: "GeneCounts" 
  outSAMtype: "BAM SortedByCoordinate"
  outSAMattributes: "Standard"

salmon:
  index_dir: "/home/gennaro/data/references/GRCh38/rmskProfiler/hg38-resources_v48/rmsk-salmon_index"
  lib_type: "A"
  gibbs: 100
  extra_params: "--gcBias --seqBias --posBias"

rustqc:
  gtf: "/home/gennaro/data/references/GRCh38/GENCODE/v48/gencode.v48.basic.annotation.gtf"
  biotype: "gene_type"
  stranded: "unstranded"

mosdepth:
  window_size: 500
  extra_params: "--fast-mode"
  include_flag: 3