import pandas as pd


configfile: "config.yaml"

SAMPLES = pd.read_csv("samples.csv", sep=",", header=0)
SAMPLES_LIST = SAMPLES["sample_name"].tolist()

WORK_DIR = "../data"
FASTP_OUT = f"{WORK_DIR}/fastp"
STAR_OUT = f"{WORK_DIR}/star"
SALMON_OUT = f"{WORK_DIR}/salmon"
MOSDEPTH_OUT = f"{WORK_DIR}/mosdepth"
RUSTQC_OUT = f"{WORK_DIR}/rustqc"
MULTIQC_OUT = f"{WORK_DIR}/multiqc"


rule all:
    input:
        f"{MULTIQC_OUT}/multiqc_report.html"


rule fastp:
    input:
        r1 = lambda w: SAMPLES.loc[SAMPLES["sample_name"] == w.sample, "read1"].item(),
        r2 = lambda w: SAMPLES.loc[SAMPLES["sample_name"] == w.sample, "read2"].item()
    output:
        r1_out = temp(f"{FASTP_OUT}/{{sample}}.trimmed.1.fq.gz"),
        r2_out = temp(f"{FASTP_OUT}/{{sample}}.trimmed.2.fq.gz"),
        html = f"{FASTP_OUT}/{{sample}}.fastp.html",
        json = f"{FASTP_OUT}/{{sample}}.fastp.json"
    log:
        f"{FASTP_OUT}/{{sample}}_fastp.log"
    params:
        extra = config["fastp"]["extra_params"]
    threads:
        12
    shell:
        """
        fastp -i {input.r1} \
              -I {input.r2} \
              -o {output.r1_out} \
              -O {output.r2_out} \
              --thread {threads} \
              {params.extra} \
              --html {output.html} \
              --json {output.json} &> {log}
        """


rule star:
    priority: 
        50
    input:
        r1 = f"{FASTP_OUT}/{{sample}}.trimmed.1.fq.gz",
        r2 = f"{FASTP_OUT}/{{sample}}.trimmed.2.fq.gz"
    output:
        bam = f"{STAR_OUT}/{{sample}}.Aligned.sortedByCoord.out.bam",
        log_final = f"{STAR_OUT}/{{sample}}.Log.final.out"
    log:
        f"{STAR_OUT}/{{sample}}/star.log"
    threads: 
        12
    params:
        star_index = config["star"]["index_dir"],
        out_prefix = f"{STAR_OUT}/{{sample}}.",
        read_cmd = config["star"]["readFilesCommand"],
        two_pass = config["star"]["twopassMode"],
        multi_mappers = config["star"]["outFilterMultimapNmax"],
        multi_anchor = config["star"]["winAnchorMultimapNmax"],
        sj_overhang_min = config["star"]["alignSJoverhangMin"],
        sjdb_overhang_min = config["star"]["alignSJDBoverhangMin"],
        mismatches = config["star"]["outFilterMismatchNmax"],
        mismatch_ratio = config["star"]["outFilterMismatchNoverLmax"],
        intron_min = config["star"]["alignIntronMin"],
        intron_max = config["star"]["alignIntronMax"],
        max_gap = config["star"]["alignMatesGapMax"],
        min_score_ratio = config["star"]["outFilterScoreMinOverLread"],
        min_match_ratio = config["star"]["outFilterMatchNminOverLread"],
        n_junctions = config["star"]["limitSjdbInsertNsj"],
        strand_field = config["star"]["outSAMstrandField"],
        quant_mode = config["star"]["quantMode"],
        out_type = config["star"]["outSAMtype"],
        sam_attributes = config["star"]["outSAMattributes"]
    shell:
      """
      STAR --genomeDir {params.star_index} \
        --readFilesIn {input.r1} {input.r2} \
        --outFileNamePrefix {params.out_prefix} \
        --runThreadN {threads} \
        --readFilesCommand {params.read_cmd} \
        --twopassMode {params.two_pass} \
        --outFilterMultimapNmax {params.multi_mappers} \
        --winAnchorMultimapNmax {params.multi_anchor} \
        --alignSJoverhangMin {params.sj_overhang_min} \
        --alignSJDBoverhangMin {params.sjdb_overhang_min} \
        --outFilterMismatchNmax {params.mismatches} \
        --outFilterMismatchNoverLmax {params.mismatch_ratio} \
        --alignIntronMin {params.intron_min} \
        --alignIntronMax {params.intron_max} \
        --alignMatesGapMax {params.max_gap} \
        --outFilterScoreMinOverLread {params.min_score_ratio} \
        --outFilterMatchNminOverLread {params.min_match_ratio} \
        --limitSjdbInsertNsj {params.n_junctions} \
        --outSAMstrandField {params.strand_field} \
        --quantMode {params.quant_mode} \
        --outSAMtype {params.out_type} \
        --outSAMattributes {params.sam_attributes} &> {log} && 
        samtools index {output.bam}
       """


rule salmon:
    priority:
        60
    input:
        r1 = f"{FASTP_OUT}/{{sample}}.trimmed.1.fq.gz",
        r2 = f"{FASTP_OUT}/{{sample}}.trimmed.2.fq.gz", 
    output:
        quant_sf = f"{SALMON_OUT}/{{sample}}/quant.sf",
        lib_format_counts = f"{SALMON_OUT}/{{sample}}/lib_format_counts.json"
    log:
        f"{SALMON_OUT}/{{sample}}/salmon.log"
    params:
        salmon_index = config["salmon"]["index_dir"],
        extra = config["salmon"]["extra_params"],
        lib_type = config["salmon"]["lib_type"],
        gibbs = config["salmon"]["gibbs"],
        output_dir = f"{SALMON_OUT}/{{sample}}"
    threads:
        12
    shell:
      """
        salmon quant \
          --index {params.salmon_index} \
          --libType {params.lib_type} \
          --mates1 {input.r1} \
          --mates2 {input.r2} \
          --threads {threads} \
          --numGibbsSamples {params.gibbs} \
          --output {params.output_dir} {params.extra} &> {log}
      """


rule mosdepth:
    priority:
        50
    input:
        bam = f"{STAR_OUT}/{{sample}}.Aligned.sortedByCoord.out.bam"
    output:
        dist = f"{MOSDEPTH_OUT}/{{sample}}.mosdepth.global.dist.txt",
        summary = f"{MOSDEPTH_OUT}/{{sample}}.mosdepth.summary.txt",
        per_base = f"{MOSDEPTH_OUT}/{{sample}}.per-base.bed.gz",
        regions = f"{MOSDEPTH_OUT}/{{sample}}.regions.bed.gz"
    params:
        prefix = f"{MOSDEPTH_OUT}/{{sample}}",
        window = config["mosdepth"]["window_size"],
        include_flag = config["mosdepth"]["include_flag"], 
        extra_params = config["mosdepth"]["extra_params"]
    log:
        f"{MOSDEPTH_OUT}/{{sample}}/mosdepth.log"
    threads:
        6
    shell:
        """
        mosdepth \
          --threads {threads} \
          --by {params.window} \
          --include-flag {params.include_flag} \
          {params.extra_params} \
          {params.prefix} \
          {input.bam} &> {log}
        """


rule rustqc:
    input:
        bam = f"{STAR_OUT}/{{sample}}.Aligned.sortedByCoord.out.bam",
        bai = f"{STAR_OUT}/{{sample}}.Aligned.sortedByCoord.out.bam.bai"
    output:
        json = f"{RUSTQC_OUT}/{{sample}}/{{sample}}_summary.json"
    params:
        gtf = config["rustqc"]["gtf"],
        biotype = config["rustqc"]["biotype"],
        stranded = config["rustqc"]["stranded"],
        outdir = f"{RUSTQC_OUT}/{{sample}}",
    threads: 
        8
    shell:
        """
        rustqc rna {input.bam} \
        --gtf {params.gtf} \
        --sample-name {wildcards.sample} \
        --json-summary {output.json} \
        --stranded {params.stranded} \
        --paired \
        --skip-dup-check \
        --biotype-attribute {params.biotype} \
        --threads {threads} \
        --outdir {params.outdir}
        """


rule multiqc_report:
    input:
        expand(f"{FASTP_OUT}/{{sample}}.fastp.html", sample=SAMPLES_LIST),
        expand(f"{STAR_OUT}/{{sample}}.Log.final.out", sample=SAMPLES_LIST),
        expand(f"{SALMON_OUT}/{{sample}}/quant.sf", sample=SAMPLES_LIST),
        expand(f"{MOSDEPTH_OUT}/{{sample}}.mosdepth.summary.txt", sample=SAMPLES_LIST),
        expand(f"{RUSTQC_OUT}/{{sample}}/{{sample}}_summary.json", sample=SAMPLES_LIST)
    output:
        html_report = f"{MULTIQC_OUT}/multiqc_report.html",
        data_dir = directory(f"{MULTIQC_OUT}/multiqc_data")
    log:
        f"{MULTIQC_OUT}/multiqc.log"
    params:
        search_dir = WORK_DIR,
        output_dir = MULTIQC_OUT
    conda:
        "multiqc"
    shell:
        "multiqc {params.search_dir} -o {params.output_dir} &> {log}"
