import pandas as pd
import os

configfile: "config.yaml"

SAMPLES = pd.read_csv("samples.csv", sep=",", header=0)
SAMPLES_LIST = SAMPLES["sample_name"].tolist()

WORK_DIR = "../data"
FASTP_OUT = f"{WORK_DIR}/fastp"
BOWTIE2_OUT = f"{WORK_DIR}/bowtie2"
GENRICH_OUT = f"{WORK_DIR}/genrich"
BIGWIG_OUT = f"{WORK_DIR}/bg2bw"
DEEPTOOLS_OUT = f"{WORK_DIR}/deeptools"
FEATURECOUNTS_OUT = f"{WORK_DIR}/featurecounts"
MULTIQC_OUT = f"{WORK_DIR}/multiqc"


rule all:
    input:
        f"{MULTIQC_OUT}/multiqc_report.html",
        expand(f"{BIGWIG_OUT}/{{sample}}.bw", sample=SAMPLES_LIST),
        expand(f"{GENRICH_OUT}/{{sample}}.narrowPeak", sample=SAMPLES_LIST),
        expand(f"{DEEPTOOLS_OUT}/{{sample}}.profile.pdf", sample=SAMPLES_LIST),
        expand(f"{DEEPTOOLS_OUT}/{{sample}}.fragSizes.pdf", sample=SAMPLES_LIST),
        expand(f"{FEATURECOUNTS_OUT}/{{sample}}.featurecounts.txt", sample=SAMPLES_LIST)


rule fastp:
    input:
        r1 = lambda w: SAMPLES.loc[SAMPLES["sample_name"] == w.sample, "read1"].values[0],
        r2 = lambda w: SAMPLES.loc[SAMPLES["sample_name"] == w.sample, "read2"].values[0]
    output:
        r1_out = temp(f"{FASTP_OUT}/{{sample}}.trimmed.1.fq.gz"),
        r2_out = temp(f"{FASTP_OUT}/{{sample}}.trimmed.2.fq.gz"),
        html = f"{FASTP_OUT}/{{sample}}.fastp.html",
        json = f"{FASTP_OUT}/{{sample}}.fastp.json"
    log:
        f"{FASTP_OUT}/{{sample}}_fastp.log"
    params:
        extra = config.get("fastp", {}).get("extra_params", "")
    threads: 8
    shell:
        """
        fastp -i {input.r1} \
              -I {input.r2} \
              -o {output.r1_out} \
              -O {output.r2_out} \
              --thread {threads} \
              {params.extra} \
              --html {output.html} \
              --json {output.json} &> {log}
        """


rule bowtie2:
    input:
        r1 = f"{FASTP_OUT}/{{sample}}.trimmed.1.fq.gz",
        r2 = f"{FASTP_OUT}/{{sample}}.trimmed.2.fq.gz"
    output:
        bam = f"{BOWTIE2_OUT}/{{sample}}.sorted.bam",
        stats = f"{BOWTIE2_OUT}/{{sample}}.stats.txt",
        idx = f"{BOWTIE2_OUT}/{{sample}}.sorted.bam.csi"
    log:
        f"{BOWTIE2_OUT}/{{sample}}.log"
    threads: 8
    params:
        idx = config["bowtie2"]["idx"],
        max_insert = config["bowtie2"]["max_insert"],
        flags = config["bowtie2"]["flags"],
        sort_mem = "4G",
        comp_threads = 4
    shell:
        """
        bowtie2 -x {params.idx} \
            -1 {input.r1} \
            -2 {input.r2} \
            {params.flags} \
            --threads {threads} \
            --maxins {params.max_insert} 2> {log} | \
        samtools view -u -h -e 'rname != "chrM" && rname != "MT"' - | \
        samtools collate -u -O -@ {params.comp_threads} - | \
        samtools fixmate -m -u -@ {params.comp_threads} - - | \
        samtools sort -u -@ {params.comp_threads} -m {params.sort_mem} - | \
        samtools markdup --write-index -f {output.stats} -@ {threads} - {output.bam} 
        """


rule collate_bam:
    input:
        position_sorted = f"{BOWTIE2_OUT}/{{sample}}.sorted.bam"
    output:
        name_sorted = temp(f"{GENRICH_OUT}/{{sample}}.bam")
    params: 
        reads = 100000
    threads: 4
    shell:
        "samtools collate -r {params.reads} -@ {threads} -o {output.name_sorted} {input.position_sorted}"


rule genrich:
    input:
        bam = f"{GENRICH_OUT}/{{sample}}.bam"
    output:
        peaks = f"{GENRICH_OUT}/{{sample}}.narrowPeak",
        pileup = f"{GENRICH_OUT}/{{sample}}.pileup.txt",
        log = f"{GENRICH_OUT}/{{sample}}.log"
    params:
         blacklist = config["genrich"]["blacklist"],
         flags = config["genrich"]["flags"]
    shell:
        """
        Genrich \
          -t {input.bam} \
          -o {output.peaks} \
          -k {output.pileup} \
          -f {output.log} \
          -E {params.blacklist} \
          -j \
          {params.flags}
        """


rule pileup2bedgraph:
    input:
        pileup = f"{GENRICH_OUT}/{{sample}}.pileup.txt"
    output:
        bedgraph = temp(f"{BIGWIG_OUT}/{{sample}}.bedGraph")
    shell:
        """
        awk 'NR > 2 {{ print $1, $2, $3, $4 }}' {input.pileup} | \
        LC_ALL=C sort -k1,1 -k2,2n > {output.bedgraph}
        """


rule bg2bw:
    input:
        bedgraph = f"{BIGWIG_OUT}/{{sample}}.bedGraph"
    output:
        bw = f"{BIGWIG_OUT}/{{sample}}.bw"
    params:
        chrom_sizes = config["bedgraph2bigwig"]["chrom_sizes"]
    shell:
        "bedGraphToBigWig {input.bedgraph} {params.chrom_sizes} {output.bw}"


rule compute_matrix:
    input:
        bigwig = f"{BIGWIG_OUT}/{{sample}}.bw"
    output:
        mat = f"{DEEPTOOLS_OUT}/{{sample}}.tss.mat.gz"
    params:
        upstream = 3000,
        downstream = 3000,
        blacklist = config["deeptools"]["blacklist"],
        gtf = config["deeptools"]["gtf"]
    conda:
        "deeptools"
    shell:
        """
        computeMatrix reference-point \
            --regionsFileName {params.gtf} \
            --scoreFileName {input.bigwig} \
            --outFileName {output.mat} \
            --referencePoint TSS \
            --beforeRegionStartLength {params.upstream} \
            --afterRegionStartLength {params.downstream} \
            --blackListFileName {params.blacklist} \
            --skipZeros \
            --missingDataAsZero \
            --metagene \
            --transcriptID gene \
            --numberOfProcessors {threads}
        """


rule plot_profile:
    input:
        mat = f"{DEEPTOOLS_OUT}/{{sample}}.tss.mat.gz"
    output:
        pdf = f"{DEEPTOOLS_OUT}/{{sample}}.profile.pdf"
    conda:
        "deeptools"
    shell:
        """
        plotProfile --matrixFile {input.mat} \
            --outFileName {output.pdf} \
            --plotTitle 'TSS enrichment' \
            --plotFileFormat 'pdf'
        """


rule fragment_size:
    input:
        bam = f"{BOWTIE2_OUT}/{{sample}}.sorted.bam",
        idx = f"{BOWTIE2_OUT}/{{sample}}.sorted.bam.csi"
    output:
        pdf = f"{DEEPTOOLS_OUT}/{{sample}}.fragSizes.pdf"
    params:
        max_len = 2000,
        blacklist = config["deeptools"]["blacklist"]
    threads:
        6
    conda:
        "deeptools"
    shell:
        """
        bamPEFragmentSize --bamfiles {input.bam} \
            --histogram {output.pdf} \
            --plotFileFormat 'pdf' \
            --numberOfProcessors {threads} \
            --maxFragmentLength {params.max_len} \
            --blackListFileName {params.blacklist}
        """


rule promoter_saf:
    input:
        gtf = config["deeptools"]["gtf"] 
    output:
        saf = f"{FEATURECOUNTS_OUT}/promoters.saf"
    params:
        upstream = 2000, 
        downstream = 2000
    shell:
        """
        zcat {input.gtf} | awk -F'\t' '
        BEGIN {{
            OFS="\t"; 
            # Print the required SAF header
            print "GeneID", "Chr", "Start", "End", "Strand";
            
            up = {params.upstream};       # Base pairs upstream of TSS
            down = {params.downstream};   # Base pairs downstream of TSS
        }}
        !/^#/ && $3 == "gene" {{
            # Extract the gene_id from the attributes column ($9)
            split($9, a, "gene_id \\""); 
            split(a[2], b, "\\""); 
            gene_id = b[1];
            
            # Calculate coordinates based on DNA strand
            if ($7 == "+") {{
                start = $4 - up; 
                if (start < 1) start = 1; # Prevent negative coordinates
                end = $4 + down;
            }} else if ($7 == "-") {{
                start = $5 - down; 
                if (start < 1) start = 1;
                end = $5 + up;
            }} else {{
                next; # Skip if strand is undefined
            }}
            
            # Print in SAF format
            print gene_id, $1, start, end, $7
        }}' > {output.saf}
        """


rule promoter_featurecounts:
    input:
        bam = f"{BOWTIE2_OUT}/{{sample}}.sorted.bam",
        saf = f"{FEATURECOUNTS_OUT}/promoters.saf"
    output:
        counts = f"{FEATURECOUNTS_OUT}/{{sample}}.featurecounts.txt"
    params:
        min_len = 0,
        max_len = 2000
    threads:
        8
    shell:
        """
        featureCounts \
            -a {input.saf} \
            -o {output.counts} \
            -F 'SAF' \
            -p \
            -d {params.min_len} \
            -D {params.max_len} \
            --read2pos 5 \
            -O \
            --fraction \
            --ignoreDup \
            -T {threads} \
            {input.bam}
        """


rule multiqc:
    input:
        expand(f"{FASTP_OUT}/{{sample}}.fastp.json", sample=SAMPLES_LIST),
        expand(f"{BOWTIE2_OUT}/{{sample}}.stats.txt", sample=SAMPLES_LIST),
        expand(f"{GENRICH_OUT}/{{sample}}.narrowPeak", sample=SAMPLES_LIST),
        expand(f"{FEATURECOUNTS_OUT}/{{sample}}.featurecounts.txt.summary", sample=SAMPLES_LIST)
    output:
        html_report = f"{MULTIQC_OUT}/multiqc_report.html",
        data_dir = directory(f"{MULTIQC_OUT}/multiqc_data")
    log:
        f"{MULTIQC_OUT}/multiqc.log"
    params:
        search_dir = WORK_DIR,
        output_dir = MULTIQC_OUT
    shell:
        "multiqc {params.search_dir} -o {params.output_dir} -f &> {log}"
